# Generated by Django 4.1.1 on 2022-10-05 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("article", "0003_comment"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="article", options={"ordering": ["-created_date"]},
        ),
        migrations.AlterModelOptions(
            name="comment", options={"ordering": ["-comment_date"]},
        ),
        migrations.AlterField(
            model_name="comment",
            name="article",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="article.article",
                verbose_name="Makale",
            ),
        ),
    ]
